# Generated by Django 3.1 on 2020-10-30 07:42

from django.db import migrations, models
import django.db.models.deletion
import extras.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('weight', models.PositiveSmallIntegerField(default=1000)),
                ('name', models.CharField(max_length=100)),
                ('template_language', models.CharField(default='jinja2', max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True)),
                ('type', models.ForeignKey(limit_choices_to=extras.utils.FeatureQuery('graphs'), on_delete=django.db.models.deletion.CASCADE, related_name='netbox_graphs_graph', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('type', 'weight', 'name', 'pk'),
            },
        ),
    ]
