# Generated by Django 3.1 on 2020-10-30 08:05

from django.db import migrations, models
import django.db.models.deletion
import extras.utils


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='type',
            field=models.ForeignKey(limit_choices_to=extras.utils.FeatureQuery('netbox_graphs'), on_delete=django.db.models.deletion.CASCADE, related_name='netbox_graphs_graph', to='contenttypes.contenttype'),
        ),
    ]
